version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Прокидываем порт 8000 на хост
    volumes:
      - .:/app       # Монтируем текущую директорию внутрь контейнера
    environment:
      - DATABASE_URL=sqlite:///ton_swap_db.db  # Используем SQLite


